/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AdminCredentials = IDL.Record({
  'password' : IDL.Text,
  'email' : IDL.Text,
});
export const Time = IDL.Int;
export const AdminSession = IDL.Record({
  'principal' : IDL.Principal,
  'createdAt' : Time,
  'email' : IDL.Text,
  'sessionToken' : IDL.Text,
});
export const CreateSessionResponse = IDL.Variant({
  'ok' : AdminSession,
  'failure' : IDL.Text,
  'invalidCredentials' : IDL.Null,
});
export const Experience = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'endDate' : IDL.Text,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'location' : IDL.Text,
  'startDate' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'githubUrl' : IDL.Text,
  'liveDemoUrl' : IDL.Text,
  'technologies' : IDL.Vec(IDL.Text),
  'image' : IDL.Record({ 'id' : IDL.Text, 'url' : IDL.Text }),
});
export const Skill = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'level' : IDL.Text,
  'category' : IDL.Text,
});
export const SocialLink = IDL.Record({
  'id' : IDL.Nat,
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const About = IDL.Record({ 'content' : IDL.Text });
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'read' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const AdminAuthResponse = IDL.Record({ 'isAdmin' : IDL.Bool });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAdminSession' : IDL.Func(
      [AdminCredentials],
      [CreateSessionResponse],
      [],
    ),
  'createExperience' : IDL.Func([Experience], [], []),
  'createProject' : IDL.Func([Project], [], []),
  'createSkill' : IDL.Func([Skill], [], []),
  'createSocialLink' : IDL.Func([SocialLink], [], []),
  'deleteContactMessage' : IDL.Func([IDL.Nat], [], []),
  'deleteExperience' : IDL.Func([IDL.Nat], [], []),
  'deleteProject' : IDL.Func([IDL.Nat], [], []),
  'deleteSkill' : IDL.Func([IDL.Nat], [], []),
  'deleteSocialLink' : IDL.Func([IDL.Nat], [], []),
  'getAbout' : IDL.Func([], [About], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
  'getExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
  'getSocialLinks' : IDL.Func([], [IDL.Vec(SocialLink)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasActiveSession' : IDL.Func([], [IDL.Bool], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isValidAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'loginAsAdmin' : IDL.Func([AdminCredentials], [AdminAuthResponse], []),
  'logoutAdmin' : IDL.Func([], [], []),
  'markMessageAsRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateAbout' : IDL.Func([IDL.Text], [], []),
  'updateExperience' : IDL.Func([IDL.Nat, Experience], [], []),
  'updateProject' : IDL.Func([IDL.Nat, Project], [], []),
  'updateSkill' : IDL.Func([IDL.Nat, Skill], [], []),
  'updateSocialLink' : IDL.Func([IDL.Nat, SocialLink], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AdminCredentials = IDL.Record({
    'password' : IDL.Text,
    'email' : IDL.Text,
  });
  const Time = IDL.Int;
  const AdminSession = IDL.Record({
    'principal' : IDL.Principal,
    'createdAt' : Time,
    'email' : IDL.Text,
    'sessionToken' : IDL.Text,
  });
  const CreateSessionResponse = IDL.Variant({
    'ok' : AdminSession,
    'failure' : IDL.Text,
    'invalidCredentials' : IDL.Null,
  });
  const Experience = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'endDate' : IDL.Text,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'location' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'githubUrl' : IDL.Text,
    'liveDemoUrl' : IDL.Text,
    'technologies' : IDL.Vec(IDL.Text),
    'image' : IDL.Record({ 'id' : IDL.Text, 'url' : IDL.Text }),
  });
  const Skill = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'level' : IDL.Text,
    'category' : IDL.Text,
  });
  const SocialLink = IDL.Record({
    'id' : IDL.Nat,
    'url' : IDL.Text,
    'platform' : IDL.Text,
  });
  const About = IDL.Record({ 'content' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'read' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const AdminAuthResponse = IDL.Record({ 'isAdmin' : IDL.Bool });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAdminSession' : IDL.Func(
        [AdminCredentials],
        [CreateSessionResponse],
        [],
      ),
    'createExperience' : IDL.Func([Experience], [], []),
    'createProject' : IDL.Func([Project], [], []),
    'createSkill' : IDL.Func([Skill], [], []),
    'createSocialLink' : IDL.Func([SocialLink], [], []),
    'deleteContactMessage' : IDL.Func([IDL.Nat], [], []),
    'deleteExperience' : IDL.Func([IDL.Nat], [], []),
    'deleteProject' : IDL.Func([IDL.Nat], [], []),
    'deleteSkill' : IDL.Func([IDL.Nat], [], []),
    'deleteSocialLink' : IDL.Func([IDL.Nat], [], []),
    'getAbout' : IDL.Func([], [About], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], []),
    'getExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'getProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getSkills' : IDL.Func([], [IDL.Vec(Skill)], ['query']),
    'getSocialLinks' : IDL.Func([], [IDL.Vec(SocialLink)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasActiveSession' : IDL.Func([], [IDL.Bool], ['query']),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isValidAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'loginAsAdmin' : IDL.Func([AdminCredentials], [AdminAuthResponse], []),
    'logoutAdmin' : IDL.Func([], [], []),
    'markMessageAsRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateAbout' : IDL.Func([IDL.Text], [], []),
    'updateExperience' : IDL.Func([IDL.Nat, Experience], [], []),
    'updateProject' : IDL.Func([IDL.Nat, Project], [], []),
    'updateSkill' : IDL.Func([IDL.Nat, Skill], [], []),
    'updateSocialLink' : IDL.Func([IDL.Nat, SocialLink], [], []),
  });
};

export const init = ({ IDL }) => { return []; };