/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface About { 'content' : string }
export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'read' : boolean,
  'email' : string,
  'message' : string,
}
export interface Experience {
  'id' : bigint,
  'title' : string,
  'endDate' : string,
  'description' : string,
  'company' : string,
  'location' : string,
  'startDate' : string,
}
export interface Project {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'githubUrl' : string,
  'liveDemoUrl' : string,
  'technologies' : Array<string>,
  'image' : { 'id' : string, 'url' : string },
}
export interface Skill {
  'id' : bigint,
  'name' : string,
  'level' : string,
  'category' : string,
}
export interface SocialLink {
  'id' : bigint,
  'url' : string,
  'platform' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createExperience' : ActorMethod<[Experience], undefined>,
  'createProject' : ActorMethod<[Project], undefined>,
  'createSkill' : ActorMethod<[Skill], undefined>,
  'createSocialLink' : ActorMethod<[SocialLink], undefined>,
  'deleteContactMessage' : ActorMethod<[bigint], undefined>,
  'deleteExperience' : ActorMethod<[bigint], undefined>,
  'deleteProject' : ActorMethod<[bigint], undefined>,
  'deleteSkill' : ActorMethod<[bigint], undefined>,
  'deleteSocialLink' : ActorMethod<[bigint], undefined>,
  'getAbout' : ActorMethod<[], About>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getExperiences' : ActorMethod<[], Array<Experience>>,
  'getProjects' : ActorMethod<[], Array<Project>>,
  'getSkills' : ActorMethod<[], Array<Skill>>,
  'getSocialLinks' : ActorMethod<[], Array<SocialLink>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markMessageAsRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactMessage' : ActorMethod<[string, string, string], undefined>,
  'updateAbout' : ActorMethod<[string], undefined>,
  'updateExperience' : ActorMethod<[bigint, Experience], undefined>,
  'updateProject' : ActorMethod<[bigint, Project], undefined>,
  'updateSkill' : ActorMethod<[bigint, Skill], undefined>,
  'updateSocialLink' : ActorMethod<[bigint, SocialLink], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];